pipeline:
  name: Build final-project-Placement-Management-System
  identifier: Build_sankaranarayananmurali_final_project_Placement_Management_System_1765821381378
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn clean package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        delegateSelectors:
          - docker-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: sankaranarayananmurali/final-project-Placement-Management-System
        build: <+input>
